baseURL = "https://elegant-bartik-af151d.netlify.com/"
languageCode = "en-us"
title = "Alex Mayer"

[taxonomies]
  category = "categories"
  tag = "tags"
  title = "titles"
  headline = "headlines"
  date = "dates"
  publishdate = "publishdates"